# Site settings
title:       UI/UX of Nathan Peters
email:       n8peters@gmail.com
author:      Nathan Peters
description: "The portfolio of UI/UX Designer and Developer, Nathan Peters"
baseurl:     ""
url:         "http://dv8withn8.github.io/"

# Google analytics
google_analytics: UA-54753296-1

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  false

# Social icons
show_social_icons: false
github_username: dv8withn8
twitter_username: dv8withn8
linkedin_username: n8peters

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     5
sass:
  compressed: true
